spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: shop
    password: shop

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER}
    password: ${MAILTRAP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  security:
    token:
      secret: 123456

app:
  mail:
    remetente: nao-responda@orderapi.com.br
    admin: admin@sualoja.com.br

stripe:
  api:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

delivery:
  api:
    url: https://run.mocky.io/v3/4238e8cb-8f0a-48d6-96b6-3e9a7e6d0a7f